Patient operator
fivetran/airflow-provider-fivetran pull request #57
Opened 2022-01-25 12:35 UTC by elliotdes

Adds a `FivetranPatientOperator` that waits for the Fievtran sync to finish before marking the task as completed. This is necessary for certain instances in which parallelism is limited.

2022-01-26 21:46 UTC, PubChimps commented
thank you @elliotdes, looking in this https://github.com/fivetran/airflow-provider-fivetran/pull/56 now

2022-02-04 19:18 UTC, denimalpaca requested changes
Few minor changes to the initializer would be nice. Not sure this is really standard practice for operators to wait like this, it's really more of sensor behavior I think. If you think there's a really good use case for this, then by all means go for it. Also happy to run this by the Astronomer team at large and get a sense of whether there's another way that might be better suited to operators.

2022-02-24 14:13 UTC, elliotdes commented on fivetran_provider/operators/fivetran.py
> +        timeout_seconds: int,
Done!

2022-02-24 14:13 UTC, elliotdes commented on fivetran_provider/operators/fivetran.py
> +        manual: bool = True,
Done, now matches the order used in the `FivetranOperator`

2022-02-24 14:22 UTC, elliotdes commented
@denimalpaca we have to use this operator in our DAG's due to limited parallelism in our Airflow instance.

The `FivetranSensor` works by checking the fivetran connectors initial status against future pokes. If the `FivetranSensor` begins after the connector has already finished its sync, then the sensor will hang. This is what was happening for us.

This `FivetranPatientOperator` would not be needed if the Fivetran API had unique id's for each triggered run that could then be checked explicitly. This is how [dbt Cloud](https://docs.getdbt.com/dbt-cloud/api-v2#operation/getRunById), and that works quite well for us.

2022-04-22 08:43 UTC, kieronellis commented
+1 on this - we are also experiencing this issue where the FivetranSensor starts after the connector has already finished its sync and so the FivetranSensor keeps reporting `sync_state = scheduled`.

2022-04-22 12:58 UTC, denimalpaca commented
@PubChimps do you have any input here on using the Sensor to avoid starting after the connector has finished? My only thought is to pattern the DAG differently: have the sensor and connector run in parallel, then set the next task to `trigger_rule=all_success`.

2022-06-10 09:11 UTC, elliotdes commented
@denimalpaca is there a way to guarantee two tasks running in parallel? If we take an extreme example where we have parallelism set to 1 on Airflow, then im not sure if the both tasks would trigger at the same time

2022-06-17 15:03 UTC, elliotdes commented
@denimalpaca would this operator be worth committing for people limited to 1 parallelism / Sequential Operator then?

2022-06-17 17:50 UTC, denimalpaca commented
@elliotdes ideally people aren't running production pipelines with a sequential executor, but for those who are, yes this will probably be useful!

2022-06-17 17:51 UTC, denimalpaca approved these changes

2022-06-24 19:44 UTC, PubChimps commented
Hi all, sorry for the delays here, but could you please check v 1.1.1 of the provider? @kieronellis this will solve the issues that you mentioned you have experienced

2022-12-09 18:20 UTC, closed without merging